# Pandas DataFrames exercises

In this exercise, we are using Automobile Dataset for data analysis. This Dataset has different characteristics of an auto such as body-style, wheel-base, engine-type, price, mileage, horsepower.

you can find the data in the data folder under `Automobile_data.csv` name

## Exercise 1:

From the given dataset print the first and last five rows  
![pandas_printing_first_5_rows.webp](attachment:pandas_printing_first_5_rows.webp)  
Python Pandas printing first 5 rows  

In [2]:
import pandas as pd
import pandas as pd
url ='https://raw.githubusercontent.com/hajar1-laaouina/M111-Advanced-Python-and-Database-Management/main/day01/data/Automobile_data.csv'
df = pd.read_csv(url)
df.head(5)

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

![pandas_printing_last_5_rows.webp](attachment:pandas_printing_last_5_rows.webp)  
Python Pandas printing last 5 rows

In [3]:
import pandas as pd

df.tail(5)

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

## Exercise 2:

**Clean the dataset and update the CSV file**

Replace all column values which contain `?`, `n.a`, or `NaN`.

In [4]:
df = pd.read_csv(url, na_values={
'price':["?","n.a"],
'stroke':["?","n.a"],
'horsepower':["?","n.a"],
'peak-rpm':["?","n.a"],
'average-mileage':["?","n.a"]})
print (df)

df.to_csv("D:\\Python\\Articles\\pandas\\automobile-dataset\\Automobile_data.csv")

    index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four        

## Exercise 3:
**Find the most expensive car company name**

Print most expensive car’s company name and price.

- Desired Output:

![pandas_printing_most_costly_car_name.webp](attachment:pandas_printing_most_costly_car_name.webp)

In [5]:
import pandas as pd
df = df [['company','price']][df.price==df['price'].max()]
df

company    price
35  mercedes-benz  45400.0

## Exercise 4:
**Print All Toyota Cars details**
- Desired Output:  
![pandas_printing_all_toyota_car_data.webp](attachment:pandas_printing_all_toyota_car_data.webp)

In [10]:
df

company    price
35  mercedes-benz  45400.0

In [11]:
import pandas as pd

url ='https://raw.githubusercontent.com/hajar1-laaouina/M111-Advanced-Python-and-Database-Management/main/day01/data/Automobile_data.csv'
df = pd.read_csv(url)

car_Manufacturers = df.groupby('company')

toyotaDf = car_Manufacturers.get_group('toyota')
toyotaDf

index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0

## Exercise 5:
Count total cars per company

- Desired Outcome:

![pandas_count_total_cars_per_company.webp](attachment:pandas_count_total_cars_per_company.webp)

In [12]:
import pandas as pd
df['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

## Exercise 6:
Find each company's Higesht price car

- Desired Outcome:

![pandas_printing_each_companys_higesht_price_car.webp](attachment:pandas_printing_each_companys_higesht_price_car.webp)

In [13]:
import pandas as pd

car_Manufacturers = df.groupby('company')
priceDf = car_Manufacturers['company','price'].max()
priceDf

<ipython-input-13-8374b186c3bd>:4: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  priceDf = car_Manufacturers['company','price'].max()


company    price
company                              
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

### Exercise 7:
Find the average mileage of each car making company
- Desired Output:

![pandas_printing_average_mileage_of_each_car_making_company.webp](attachment:pandas_printing_average_mileage_of_each_car_making_company.webp)

In [14]:
import pandas as pd
car_Manufacturers = df.groupby('company')
mileageDf = car_Manufacturers['company','average-mileage'].mean()
mileageDf

<ipython-input-14-10db4472eb32>:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mileageDf = car_Manufacturers['company','average-mileage'].mean()


average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

## Exercise 8:
Sort all cars by Price column

- Desired Output:

![pandas_sort_all_cars_by_price_column.webp](attachment:pandas_sort_all_cars_by_price_column.webp)

In [17]:
import pandas as pd

url ='https://raw.githubusercontent.com/hajar1-laaouina/M111-Advanced-Python-and-Database-Management/main/day01/data/Automobile_data.csv'
df = pd.read_csv(url)
carsDf = df.sort_values(by=['price', 'horsepower'], ascending=False)
carsDf.head(5)

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0

## Exercise 9:

Concatenate two data frames using the following conditions

Create two data frames using the following two dictionaries.

```python
>>> GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925, 71400]}
>>> japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500, 58900]}
```

- Desired Output:

![pandas_concatenate_two_data_frames_and_create_key_for_each_data_frame.webp](attachment:pandas_concatenate_two_data_frames_and_create_key_for_each_data_frame.webp)

In [18]:
import pandas as pd

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
carsDf1 = pd.DataFrame.from_dict(GermanCars)

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
carsDf2 = pd.DataFrame.from_dict(japaneseCars)

carsDf = pd.concat([carsDf1, carsDf2], keys=["Germany", "Japan"])
carsDf

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

## Exercise 10:

**Merge two data frames using the following condition**

Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.

```python
>>> Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
>>> car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
```

- Desired Output:

![merge_two_data_frames_and_append_new_data_frame_as_new-column.webp](attachment:merge_two_data_frames_and_append_new_data_frame_as_new-column.webp)

In [19]:
import pandas as pd

Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
carPriceDf = pd.DataFrame.from_dict(Car_Price)

car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
carsHorsepowerDf = pd.DataFrame.from_dict(car_Horsepower)

carsDf = pd.merge(carPriceDf, carsHorsepowerDf, on="Company")
carsDf

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

## Exercise 11

1. Write a Pandas program to replace NaNs with median or mean of the specified columns in a given DataFrame.
2. Write a Pandas program to replace the missing values with the most frequent values present in each column of a given DataFrame.

In [20]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,np.nan,65.26,110.5,948.5,np.nan,5760,1983.43,np.nan,250.45, 75.29,3045.6],
'sale_amt':[10.5,20.65,np.nan,11.5,98.5,np.nan,57,19.43,np.nan,25.45, 75.29,35.6],
'ord_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'salesman_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})